#!/usr/bin/env python3
"""What the network volume still holds from the r1 pod — COUNTED and PRICED, and never merged.

`docs/PROMPT-pass1-window-r2.md` §3. `/workspace/run/pass1_window_v2.jsonl` survived the r1 pod's
deletion on volume `qw4nwleanc` with at least 132 rows: the Mac holds 131 because `--watch` copies
once a poll and the KILL happened inside the loop, and the pod's own log names the 132nd
(`@klopotenkofood:6035#21205`, 759.2 s — Dv657 made concrete in the r1 census).

**It is EVIDENCE and not input.** D1 copies it back before the run directory is cleared, hashes it on
both sides, and this module says what it holds that the Mac did not:

* rows the Mac already has — nothing owed, nothing learned;
* rows the Mac does NOT have whose id is inside the 901 this contract buys: those are **bought
  twice**, and the census names the count and the cost (`n × the measured s/call`);
* rows whose id is in neither — a defect, and a refusal.

**It is never merged.** Every row it carries beyond the Mac's is inside the 901 by construction, so
merging it would put TWO answers in play for one id: the volume's, generated by a pod that was
killed, and this run's. Which one a later reader picks is an ambiguity this registration does not
buy ([[a_retry_inherits_the_last_attempts_output]]). The rows are counted, priced, and left in the
evidence file.

    PYTHONPATH=src python3.11 scripts/volume_tail_pass1_window.py \\
        --tail results/pass1_window_volume_tail.jsonl --seconds-per-call 4.5
"""

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))
sys.path.insert(0, str(Path(__file__).resolve().parent))

import window_summary_5c2 as summary  # noqa: E402

TAIL = REPO_ROOT / "results" / "pass1_window_volume_tail.jsonl"
R1_OUT = REPO_ROOT / "results" / "pass1_window_v2.jsonl"
R2_PACK = REPO_ROOT / "results" / "pass1_window_r2_pack.json"


def ids_of(path: Path) -> list[str]:
    return [
        json.loads(line)["id"]
        for line in summary.read_text_or_refuse(path).splitlines()
        if line.strip()
    ]


def account(tail: Path, r1_out: Path, pack: dict, seconds_per_call: float | None = None) -> dict:
    """The volume's file against what the Mac holds and what this contract owes."""
    owed = {one["id"] for one in pack["legs"][0]["items"]}
    held = ids_of(r1_out)
    rows = ids_of(tail)
    duplicates = sorted({one for one in rows if rows.count(one) > 1})
    if duplicates:
        raise SystemExit(
            f"{summary.rel(tail)} carries {duplicates[:5]} more than once. The volume's file is"
            " append-only evidence and a repeated id means the run directory was not cleared"
            " between attempts — stop and report."
        )
    beyond = [one for one in rows if one not in set(held)]
    stranger = sorted(one for one in beyond if one not in owed)
    if stranger:
        raise SystemExit(
            f"{summary.rel(tail)} carries {stranger[:5]}, which are neither in"
            f" {summary.rel(r1_out)} nor in the 901 this contract asks. A row that belongs to no"
            " population is a defect in the copy-back or in the volume — stop and report."
        )
    bought_twice = sorted(beyond)
    return {
        "file": summary.rel(tail),
        "sha256": summary.sha256_of(tail),
        "rows_on_the_volume": len(rows),
        "rows_the_mac_already_held": len(rows) - len(bought_twice),
        "rows_beyond_the_mac": len(bought_twice),
        "rows_beyond_the_mac_ids": bought_twice,
        "every_one_of_them_is_inside_the_901": True,
        "bought_twice_seconds": (
            round(len(bought_twice) * seconds_per_call, 2) if seconds_per_call else None
        ),
        "seconds_per_call_used": seconds_per_call,
        "merged": False,
        "rule": (
            "EVIDENCE, not input. Every row beyond the Mac's copy is inside the 901 this"
            " registration buys, so it is bought again here and the cost is named:"
            " `rows_beyond_the_mac × the measured s/call of THIS pod`. The file is never merged"
            " into the out-file — two answers for one id is an ambiguity this registration does"
            " not buy, and the second answer would come from a pod that was killed"
            " ([[a_retry_inherits_the_last_attempts_output]])"
        ),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tail", type=Path, default=TAIL)
    parser.add_argument("--r1-out", type=Path, default=R1_OUT)
    parser.add_argument("--pack", type=Path, default=R2_PACK)
    parser.add_argument("--seconds-per-call", type=float, default=None)
    args = parser.parse_args(argv)

    reading = account(
        args.tail,
        args.r1_out,
        json.loads(summary.read_text_or_refuse(args.pack)),
        args.seconds_per_call,
    )
    print(json.dumps(reading, ensure_ascii=False, indent=2, sort_keys=True))
    print(
        f"\n{reading['rows_beyond_the_mac']} rows bought twice"
        + (
            f" — {reading['bought_twice_seconds']} s at {reading['seconds_per_call_used']} s/call"
            if reading["bought_twice_seconds"] is not None
            else " (hand --seconds-per-call the pod's measured rate to price them)"
        )
        + ". NOT merged."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
